In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
import numpy as np
my_list1= [2,8,5,3]
my_list2= [7,6,8,4]
arr1=np.array(my_list1)
arr2= np.array(my_list2)
add= arr1+arr2
print (add)

[ 9 14 13  7]


In [2]:
#Addition of two arrays using numpy
import numpy as np
arr1= np.array([[1,2],[3,4]])
arr2=np.array ([[5,6],[7,8]])
sum= arr1+arr2
print ("Addition of two arrays using numpy:")
print (sum, ("\n"))


#Addition of two arrays using list
arr1=[[1,2],[3,4]]
arr2=[[5,6],[7,8]]
result=[[0,0], [0,0]]
for i in range(len(arr1)):
    for j in range (len(arr2)):
        result[i][j]= arr1[i][j] + arr2[i][j]
print ("Addition of two arrays using list:", result)

Addition of two arrays using numpy:
[[ 6  8]
 [10 12]] 

Addition of two arrays using list: [[6, 8], [10, 12]]


In [33]:
# 0-D Array
import numpy as np
arr = np.array(42)
print("1. 0-D array:", arr)
print ("Number of dimensions:", arr.ndim, ( "\n"))

#1-D Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("2. 1-D Array:", arr)
print ("Number of dimensions:", arr.ndim, ( "\n"))

#2-D Array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("3. 2-D Array:", arr)
print ("Number of dimensions:", arr.ndim, ( "\n"))

#3-D Array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("4. 3-D Array:", arr)
print ("Number of dimensions:", arr.ndim, ( "\n"))

#Higher Dimensional Array
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print("5. Higher dimension array:", arr)
print('Number of dimensions :', arr.ndim, ("\n"))

1. 0-D array: 42
Number of dimensions: 0 

2. 1-D Array: [1 2 3 4 5]
Number of dimensions: 1 

3. 2-D Array: [[1 2 3]
 [4 5 6]]
Number of dimensions: 2 

4. 3-D Array: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Number of dimensions: 3 

5. Higher dimension array: [[[[[1 2 3 4]]]]]
Number of dimensions : 5 



In [17]:
#Accessing array element (1-D Array)
import numpy as np
arr = np.array([2, 3, 4])
print("6. Accessing element of a 1-D array:", arr[0], ("\n"))


#Accessing array element (2-D Array)
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("7. Accessing element of a 2-D array (2nd element on 1st row):", arr[0, 1], ("\n"))


#Accessing array element (3-D Array)
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("8. Accessing element of a 3-D array:", arr[0, 1, 2], ("\n"))


#Negative Indexing
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("9. Negative Indexing (last element from 2nd dimension):", arr[1, -1], ("\n"))


#STEP value to determine the step of the slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print ("10. To determine the step of the slicing:", arr[1:8:2],( "\n"))


#Slicing 2-D Array
import numpy as np
arr= np.array ([[1,2,3,4,5] , [6,7,8,9,10]])
print ("11.(01). Slicing 2-D array:",arr[1, 1:4])


#Through slicing return index 2 from both element
import numpy as np
arr= np.array ([[1,2,3,4,5], [6,7,8,9,10]])
print ("11.(02). Through slicing in 2-D arry return index 2 from both element:", arr[0:2, 2])


#From both elements slice index 1 to 4 (not included) in 2-D array
import numpy as np
arr= np.array ([[1,2,3,4,5], [6,7,8,9,10]])
print ("11.(03).")
print (arr[0:2, 1:4],( "\n"))


#Data Type of an array
import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array(['cherry', 'apple', 'banana', 'chiku'])
print ("12.(01). Data type of an array:", arr1.dtype)
print ("12.(02). Data type of an array:", arr2.dtype,( "\n"))


#Converting data type on existing data type
import numpy as np
arr=np.array([1.1,2.1,3.1,4.1,5.1])
newarr=arr.astype('i')
print ("13.(01). Converting data type:", newarr)
print ("         Data type (converted) of the new array:", newarr.dtype)

import numpy as np
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print("13.(02). Converting data type:", newarr)
print("         Data type of the converted array:", newarr.dtype,( "\n"))


#Copying an array ------> Make a copy of an array and make changes in the original and display both the arrays
import numpy as np
arr=np.array([1,2,3,4,5])
x= arr.copy()
arr[0]=42
print("14. Making a copy of an array and making changes in the original array:", arr)
print("                                            Copy of the original array:", x,( "\n"))


#Viewing the array -----> Make a view, change the original array, and display both arrays
import numpy as np
arr=np.array([1,2,3,4,5])
x= arr.view()
arr[0]=36
print ("15. Make a view, change the original array, and display both arrays:", arr)
print ("                                         View of the original array:", x,( "\n"),( "\n"))


#Check if the array ows its data or not
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print("16. Checking if the array owns ists data or not (COPY):", x.base)
print("                                                (VIEW):", y.base,( "\n"))


#Shape of the array
import numpy as np
arr= np.array([[1,2,3,4,0], [5,6,7,8,0]])
print ("17. Shape of the array (2 rows and 5 columns):", arr.shape,( "\n"))


#Reshape 1-D to 2-D array
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
newarr= arr.reshape(5, 3)
print ("18. Reshaping 1-D array into a 2-D array:")
print (newarr,( "\n"))


#Reshape 1-D to 3-D array
import numpy as np
arr= np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= arr.reshape (2,3,2)
print ("19. Reshaping 1-D array into a 3-D array:")
print (newarr,( "\n"))


#Flattening the array (converting a multidimensional array into a 1D array)
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print("20. Flattening the array:", newarr,( "\n"))


#Iterating 1-D array (going through the elements of the array one by one)
import numpy as np
arr= np.array ([1,2,3])
print ("21. Iterating 1-D array:")
for x in arr:
    print (x,( "\n"))


#Iterating 2-D array
import numpy as np
arr= np.array ([[1,2,3], [4,5,6]])
print ("22. Iterating 2-D array:")
for x in arr:
    print (x,( "\n"))

#Iterating 2-D array further
import numpy as np
arr= np.array ([[1,2,3], [4,5,6]])
print ("23. Iterating 2-D array further:")
for x in arr:
    for y in x:
        print (y,( "\n"))


#Iterating 3-D array
import numpy as np
arr= np.array ([[[1,2,3],[4,5,6],[7,8,9]]])
print ("24. Iterating 3-D array:")
for x in arr:
    print (x,( "\n"))

#Iterating 3-D array further
import numpy as np
arr= np.array ([[[1,2,3],[4,5,6],[7,8,9]]])
print ("25. Iterating 3-D array further:")
for x in arr:
    for y in x:
        for z in y:
            print (z,( "\n"))



#Iterating arrays using nditer()
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print ("26. Iterating arrays using iditer():")
for x in np.nditer(arr):
  print(x,( "\n"))


#Joining two 1-D arrays
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print("27. Joining two 1-D arrays:", arr, ("\n"))


#Joining two 2-D arrays along column
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print("28. Joining two 2-D arrays along column:")
print (arr, ("\n"))


#Joining arrays using stack function
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print("29. Joining two arrays using stack function:",arr, ("\n"))


#Stacking arrays along rows using hstack() function
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print("30. Stacking arrays along rows using hstack() function:",arr, ("\n"))


#Stacking arrays along columns using vstack() function
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print("31. Stacking arrays along column using vstack() function:")
print (arr, ("\n"))


#Stacking arrays along depth using dstack() function
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print("32. Stacking arrays along depth using dstack() function:")
print (arr, ("\n"))


#Splitting the array (1-D)
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr= np.array_split(arr,3)
print("33. Splitting array (1-D):", newarr, ("\n"))


#Splitting the array (2-D)
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print ("34. Splitting the array (2-D):")
print(newarr, ("\n"))


#Splitting 2-D array along columns
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
newarr = np.array_split(arr, 3, axis=1)
print("35. Splitting arrays along columns:", newarr, ("\n"))


#Splitting arrays along columns using hsplit() function
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
newarr = np.hsplit(arr, 3)
print("36. Splitting arrays along columns using hsplit() function:", newarr, ("\n"))


#Splitting arrays along rows using vsplit() function
import numpy as np
arr= np.array([[1,2,3], [4,5,6], [7,8,9]])
newarr= np.vsplit(arr,3)
print ("37. Splitting arrays along rows using vsplit() function:", newarr,("\n"))


#Searching arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print("38. Searching index of elements in arrays:", x, ("\n"))


#Searchsorted method()
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print("39. Searching index of elements using searchsorted() element:", x, ("\n"))


#Sarching index of element from right in an array
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print("40. Searching index of element from right in an array:", x, ("\n"))


#Finding the indexes where 2,4,6 should be inserted
import numpy as np
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print("41. Finding the indexes where 2,4,6 should be inserted:", x, ("\n"))


#Sorting the elements of the array
import numpy as np
arr = np.array([6,10,5,4,8,3,1])
print("42. Sorting the elements of the array:",np.sort(arr), ("\n"))


#Sorting the elements of the array (STRING)
import numpy as np
arr= np.array(['apple', 'cherry', 'watermelon', 'chiku'])
print ("43. Sorting the elements of the array (STRING):", np.sort(arr), ("\n"))


#Sorting a 2-D array
import numpy as np
arr= np.array([[3, 2, 4], [5, 0, 1]])
print ("44. Sorting a 2-D array:")
print (np.sort(arr), ("\n"))


#Filtering arrays (Only index value having same index number as True element will be printed)
import numpy as np
arr=np.array ([41,42,43,44])
x= [True, False, True, False]
newarr= arr[x]
print ("45. Filtering array:", newarr, ("\n"))


#Creating the Filter array
import numpy as np
arr=np.array([41,42,43,44,45])
filter_arr=[]
for element in arr:
    if element >42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print ("46. Creating the filter array:", filter_arr)
print ("                             :", newarr)

6. Accessing element of a 1-D array: 2 

7. Accessing element of a 2-D array (2nd element on 1st row): 2 

8. Accessing element of a 3-D array: 6 

9. Negative Indexing (last element from 2nd dimension): 10 

10. To determine the step of the slicing: [2 4 6 8] 

11.(01). Slicing 2-D array: [7 8 9]
11.(02). Through slicing in 2-D arry return index 2 from both element: [3 8]
11.(03).
[[2 3 4]
 [7 8 9]] 

12.(01). Data type of an array: int64
12.(02). Data type of an array: <U6 

13.(01). Converting data type: [1 2 3 4 5]
         Data type (converted) of the new array: int32
13.(02). Converting data type: [ True False  True]
         Data type of the converted array: bool 

14. Making a copy of an array and making changes in the original array: [42  2  3  4  5]
                                            Copy of the original array: [1 2 3 4 5] 

15. Make a view, change the original array, and display both arrays: [36  2  3  4  5]
                                         View of the origi